# Use an official Python runtime as a parent image
FROM ghcr.io/mlflow/mlflow:v2.10.2

# Set the working directory in the container
WORKDIR /app

# Install PyTorch and MLflow
RUN pip install torch torchvision mlflow
