# Use an official Python runtime as a parent image
FROM ghcr.io/devexpgbb/devcontainer-base:sha-bc2a987bd5d342557cb4efab67d44079d97dd701

# Set the working directory in the container
WORKDIR /app

# Install PyTorch and MLflow
RUN pip install torch torchvision mlflow
